[FEATURE #13] Add Junit to the project
nukesz/snake pull request #16
Opened 2017-07-31 21:14 UTC by saznetro

- Add JUnit 4 to Core
- Create conventional directory structure
- Remove warnings

2017-08-01 10:33 UTC, nukesz requested changes

2017-08-01 10:33 UTC, nukesz commented on core/build.gradle
> +}
You can set in IntelliJ to always add an empty line as the file. (git works better if you have it)

2017-08-01 10:33 UTC, nukesz commented on core/src/main/java/com/nukesz/game/Item.java
> +public class Item {
It's a good idea to create a base class, but maybe you could call it as AbstractGameObject. (as others do in libgdx)

2017-08-01 10:33 UTC, nukesz commented on core/src/test/java/BodyPartTest.java
> +        //GIVEN
Don't need

2017-08-01 10:33 UTC, nukesz commented on core/src/test/java/BodyPartTest.java
> +        //WHEN/THEN
Don't need

2017-08-01 10:33 UTC, nukesz commented on core/src/test/java/BodyPartTest.java
> +        Assert.assertEquals(2, bp.getY());
you can do static import

2017-08-01 10:33 UTC, nukesz commented on core/src/main/java/com/nukesz/game/BodyPart.java
> +    public int getY() {
in libgdx, they are not really adding getters and setters. They prefer to have public fields. It's not just performance, but usually a class can have 5-10+ fields, and a setters and getters adding noise around it.  

It's easier to write 
car.speed += 10;

then
car.setSpeed(car.getSpeed() + 10);

2017-08-01 10:49 UTC, saznetro commented on core/build.gradle
> +}
Please share your formatter configuration and add it to the git source.

2017-08-01 10:52 UTC, saznetro commented on core/src/main/java/com/nukesz/game/BodyPart.java
> +    public int getY() {
In that sense, then it should be car.adjustSpeedBy(10); or car.adjustSpeedBy(-10);  could work. 
But I accept and I will change it back as I didn't know this was the reason.

2017-08-01 19:34 UTC, nukesz requested changes

2017-08-01 19:34 UTC, nukesz commented on core/build.gradle
> +}
The dependency should be in the main build.gradle. Where we have all dependencies for the core/desktop project.

2017-08-01 19:34 UTC, nukesz commented on desktop/build.gradle
>  sourceCompatibility = 1.6
Maybe this should be changed also to 1.7

2017-08-01 19:34 UTC, nukesz commented on core/src/test/java/BodyPartTest.java
> +        Assert.assertEquals(2, bp.y);
You can use static import.

2017-08-01 19:34 UTC, nukesz commented on core/src/test/java/BodyPartTest.java
> +    public void test() {
Maybe this can be renamed something meaningful

2017-08-02 06:48 UTC, nukesz approved these changes

2017-08-02 06:48 UTC, merged